Compose UI
Lvntt/Calculator pull request #4
Opened 2023-03-05 11:09 UTC by Lvntt

Added compose UI & MVVM

2023-03-10 10:33 UTC, Chantreck requested changes
На этот раз из-за перехода на компоуз пришлось начинать практически с нуля, поэтому логику и стиль кода не особо смотрел, оставим на следующий раз

2023-03-10 10:33 UTC, Chantreck commented on app/src/main/res/drawable/button_shape.xml
> +<shape xmlns:android="http://schemas.android.com/apk/res/android"
Если ты на компоуз перешёл, зачем этот файл?)

2023-03-10 10:33 UTC, Chantreck commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +            viewModel = viewModel,
Не нужно передавать `viewModel` в компонент. Либо у компонента есть своя `ViewModel` (обычно, если это либо компонент экрана, либо компонент со сложной логикой), либо в компонент передаётся только лямбда для `onClick`. Можно передать либо непосредственно в виде лямбды, либо через `Modifier.clickable()` с `when` внутри (я больше за первый вариант в данном случае). Делать так нужно, потому что кнопка не должна знать, что существует какая-то вью-модель, которая будет обрабатывать нажатие кнопки. Кнопка просто говорит: вот я могу нажаться, при нажатии нужно сделать какое-то действие, всё остальное её мало волнует. К тому же одни и те же кнопки могут быть на разных экранах, а значит у них будут разные вью-модели

2023-03-10 10:33 UTC, Chantreck commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +    viewModel: CalculatorViewModel,
Здесь можно обойтись без передачи всей вью-модели, достаточно просто передать UiState и выражение

2023-03-10 10:33 UTC, Chantreck commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +    viewModel: CalculatorViewModel,
Здесь заменяем вью-модель на `onIconClick: () -> Unit`

2023-03-10 10:33 UTC, Chantreck commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +        if (buttonsRow.size == 3) {
В идеале здесь тоже проходиться циклом по кнопкам. Условие на размер ряда нужно только для 1 или 1-2 кнопок, остальные кнопки никак от него не зависят, надо их вынести из условия

2023-03-10 10:33 UTC, Chantreck commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +    viewModel: CalculatorViewModel,
Здесь совершенно точно не нужна вью-модель, достаточно просто заменить на `onClick: (CalculatorButton) -> Unit`

2023-03-10 10:33 UTC, Chantreck commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +            buttonsGrid = ButtonsSource.buttons
Если используешь MVVM, то в идеале получить кнопки от `ViewModel`, которая будет брать их из модели (например, как у тебя из `ButtonSource`)

2023-03-10 10:33 UTC, Chantreck commented on app/src/main/java/com/example/calculator/model/CalculatorModel.kt
> +        CalculatorButton.ADDITION.value[0],
Чтобы не делать так, у `value` можно изначально задать тип `Char`

2023-03-10 10:33 UTC, Chantreck commented on app/src/main/java/com/example/calculator/presentation/CalculatorUiState.kt
> +    object Input : CalculatorUiState
В этих объектах можно было бы инкапсулировать сразу и значение выражения, поскольку у тебя `UiState` всегда будет обновляться вместе с `currentExpression`, поэтому логично иметь их вместе. Для этого можно `object`, например, заменить на `data class`. Для ошибки можно даже задать дефолтное значение сообщения, раз оно у тебя как правило не меняется

2023-03-10 10:33 UTC, Chantreck commented on app/src/main/java/com/example/calculator/presentation/CalculatorViewModel.kt
> +                _currentExpression.value = calculatorModel.handleOperationClick(button.value)
А зачем передавать в модель строку? Передавай тот же CalculatorButton, опять-таки обезопасишь handleOperationClick, поскольку сразу будет сильно ограничены возможные входные данные, а если надо получить сам знак, уже внутри модели можешь его взять.

2023-03-10 10:33 UTC, Chantreck commented on app/src/main/java/com/example/calculator/model/CalculatorModel.kt
> +            canResetExpression = false
Всё же кажется, что если хранить операнды по отдельности, то не нужно будет придумывать такие обходы в виде `CharArray` и прочего, выглядит очень экстравагантно)

2023-03-10 10:53 UTC, Lvntt commented on app/src/main/java/com/example/calculator/model/CalculatorModel.kt
> +            canResetExpression = false
Не спорю, делать через регулярку было не лучшей идеей, но почему-то захотелось в качестве эксперимента.

2023-03-15 06:23 UTC, Chantreck commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +class MainActivity : ComponentActivity() {
Пробельчика не хватает перед объявлением класса

2023-03-15 06:23 UTC, Chantreck commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +            buttonsGrid = viewModel.getButtons(),
Здесь наверное тоже стоит по ссылке передавать, раз ты в остальных местах так делаешь

2023-03-15 06:23 UTC, Chantreck commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +    Row(modifier = modifier) {
По-моему `Row` лишний, можно было бы без него, чтобы лишних вложенностей не было

2023-03-15 06:23 UTC, Chantreck commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +        when (calculatorUiState) {
Красивое решение, я прям кайфанул)

2023-03-15 06:23 UTC, Chantreck commented on app/src/main/java/com/example/calculator/presentation/CalculatorViewModel.kt
> +    private fun setError() {
Обычно сначала размещают все публичные функции, а затем уже защищенные и приватные (обычно в порядке вызова из публичных)

2023-03-15 06:23 UTC, Chantreck commented on app/src/main/java/com/example/calculator/model/CalculatorModel.kt
> +        private const val TAG = "CALCULATOR"
Чтобы не писать кучу раз private, можно завести отдельно `private companion object`, тогда все его члены автоматически будут приватными. И да, у класса может быть несколько companion object, но ERROR_MESSAGE возможно есть смысл просто вынести в отдельный объект, так как используется несколькими классами

2023-03-15 06:24 UTC, Chantreck approved these changes

2023-03-22 15:47 UTC, merged